- branchNamePattern: '(feature|bugfix)/.*'
  environment: 'PREDEV'
- branchNamePattern: '(develop|hotfix/.*)'
  environment: 'DEV'
- branchNamePattern: 'preqa'
  environment: 'PREQA'
- branchNamePattern: 'sbx'
  environment: 'SBX'
- branchNamePattern: 'release'
  environment: 'QA'
- branchNamePattern: 'master'
  environment: 'PROD'