// appSagas / appReducer
export const SET_APP_READY = "setAppReady";
export const UPDATE_APP_READY = "updateAppReady";

export const ADD_FORM_VALUES = "addFormValues";
export const CLEAR_FORM_VALUES = "clearFormValues";
// export const CLEAR_FORM_VALUES = "clearFormValues";

interface AuthActionTypes {
  GROUP: {
    ADD_GROUP_REQUEST: string;
    ADD_GROUP_SUCCESS: string;
    ADD_GROUP_FAILURE: string;

    GET_GROUP_REQUEST: string;
    GET_GROUP_SUCCESS: string;
    GET_GROUP_FAILURE: string;

    UPDATE_GROUP_REQUEST: string;
    UPDATE_GROUP_SUCCESS: string;
    UPDATE_GROUP_FAILURE: string;

    DELETE_GROUP_REQUEST: string;
    DELETE_GROUP_SUCCESS: string;
    DELETE_GROUP_FAILURE: string;
  };
  PERMISSION: {
    ADD_PERMISSION_REQUEST: string;
    ADD_PERMISSION_SUCCESS: string;
    ADD_PERMISSION_FAILURE: string;

    GET_PERMISSION_GROUP_REQUEST: string;
    GET_PERMISSION_GROUP_SUCCESS: string;
    GET_PERMISSION_GROUP_FAILURE: string;
    REFRESH_PERMISSION_COUNTER: string;

     // Permission List Management
    GET_PERMISSIONS_REQUEST: string;
    GET_PERMISSIONS_SUCCESS: string;
    GET_PERMISSIONS_FAILURE: string;

    CREATE_PERMISSION_REQUEST: string;
    CREATE_PERMISSION_SUCCESS: string;
    CREATE_PERMISSION_FAILURE: string;

    DELETE_PERMISSION_REQUEST: string;
    DELETE_PERMISSION_SUCCESS: string;
    DELETE_PERMISSION_FAILURE: string;
  };
  TASK: {
    GET_TASK_REQUEST: string;
    GET_TASK_SUCCESS: string;
    GET_TASK_FAILURE: string;
    ADD_TASK_REQUEST: string;
    ADD_TASK_SUCCESS: string;
    UPDATE_TASK_FAILURE: string;
    UPDATE_TASK_REQUEST: string;
    UPDATE_TASK_SUCCESS: string;
    DELETE_TASK_FAILURE: string;
    DELETE_TASK_REQUEST: string;
    DELETE_TASK_SUCCESS: string;
    ADD_TASK_FAILURE: string;
    GET_TASK_CATEGORY_REQUEST: string;
    GET_TASK_CATEGORY_SUCCESS: string;
    GET_TASK_CATEGORY_FAILURE: string;
    GET_TASK_SUBCATEGORY_REQUEST: string;
    GET_TASK_SUBCATEGORY_SUCCESS: string;
    GET_TASK_SUBCATEGORY_FAILURE: string;
  };
  USER: {
    GET_USER_REQUEST: string;
    GET_USER_SUCCESS: string;
    GET_USER_FAILURE: string;

    GET_USERS_REQUEST: string;
    GET_USERS_SUCCESS: string;
    GET_USERS_FAILURE: string;

    CREATE_USER_REQUEST: string;
    CREATE_USER_SUCCESS: string;
    CREATE_USER_FAILURE: string;

    UPDATE_USER_REQUEST: string;
    UPDATE_USER_SUCCESS: string;
    UPDATE_USER_FAILURE: string;

    DELETE_USER_REQUEST: string;
    DELETE_USER_SUCCESS: string;
    DELETE_USER_FAILURE: string;

    SELECT_USER: string;
    SELECT_ALL_USERS: string;
    CLEAR_SELECTED_USERS: string;

    GET_USERS_ACTIVITY_LOG_REQUEST: string;
    GET_USERS_ACTIVITY_LOG_SUCCESS: string;
    GET_USERS_ACTIVITY_LOG_FAILURE: string;

    
    GET_USER_PERMISSION_DETAILS_REQUEST: string;
    GET_USER_PERMISSION_DETAILS_SUCCESS: string;
    GET_USER_PERMISSION_DETAILS_FAILURE: string;

    
    DELETE_USER_PERMISSION_DETAIL_REQUEST: string;
    DELETE_USER_PERMISSION_DETAIL_SUCCESS: string;
    DELETE_USER_PERMISSION_DETAIL_FAILURE: string;

    ASSIGN_USER_PERMISSIONS_REQUEST: string;
    ASSIGN_USER_PERMISSIONS_SUCCESS: string;
    ASSIGN_USER_PERMISSIONS_FAILURE: string;

    FETCH_GLOBAL_PERMISSIONS_REQUEST: string;
    FETCH_GLOBAL_PERMISSIONS_SUCCESS: string;
    FETCH_GLOBAL_PERMISSIONS_FAILURE: string;

  };
  AUDIT: {
    GET_AUTH_AUDIT_LOG_REQUEST: string;
    GET_AUTH_AUDIT_LOG_SUCCESS: string;
    GET_AUTH_AUDIT_LOG_FAILURE: string;
  };
}

export const AUTH: AuthActionTypes = {
  GROUP: {
    ADD_GROUP_REQUEST: "ADD_GROUP_REQUEST",
    ADD_GROUP_SUCCESS: "ADD_GROUP_SUCCESS",
    ADD_GROUP_FAILURE: "ADD_GROUP_FAILURE",

    GET_GROUP_REQUEST: "GET_GROUP_REQUEST",
    GET_GROUP_SUCCESS: "GET_GROUP_SUCCESS",
    GET_GROUP_FAILURE: "GET_GROUP_FAILURE",

    UPDATE_GROUP_REQUEST: "UPDATE_GROUP_REQUEST",
    UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",
    UPDATE_GROUP_FAILURE: "UPDATE_GROUP_FAILURE",

    DELETE_GROUP_REQUEST: "DELETE_GROUP_REQUEST",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE",
  },
  PERMISSION: {
    ADD_PERMISSION_REQUEST: "ADD_PERMISSION_REQUEST",
    ADD_PERMISSION_SUCCESS: "ADD_PERMISSION_SUCCESS",
    ADD_PERMISSION_FAILURE: "ADD_PERMISSION_FAILURE",

    GET_PERMISSION_GROUP_REQUEST: "GET_PERMISSION_GROUP_REQUEST",
    GET_PERMISSION_GROUP_SUCCESS: "GET_PERMISSION_GROUP_SUCCESS",
    GET_PERMISSION_GROUP_FAILURE: "GET_PERMISSION_GROUP_FAILURE",
    REFRESH_PERMISSION_COUNTER: "REFRESH_PERMISSION_COUNTER",

    GET_PERMISSIONS_REQUEST: "GET_PERMISSIONS_REQUEST",
    GET_PERMISSIONS_SUCCESS: "GET_PERMISSIONS_SUCCESS",
    GET_PERMISSIONS_FAILURE: "GET_PERMISSIONS_FAILURE",

    CREATE_PERMISSION_REQUEST: "CREATE_PERMISSION_REQUEST",
    CREATE_PERMISSION_SUCCESS: "CREATE_PERMISSION_SUCCESS",
    CREATE_PERMISSION_FAILURE: "CREATE_PERMISSION_FAILURE",

    DELETE_PERMISSION_REQUEST: "DELETE_PERMISSION_REQUEST",
    DELETE_PERMISSION_SUCCESS: "DELETE_PERMISSION_SUCCESS",
    DELETE_PERMISSION_FAILURE: "DELETE_PERMISSION_FAILURE",
  },
  TASK: {
    GET_TASK_REQUEST: "GET_TASK_REQUEST",
    GET_TASK_SUCCESS: "GET_TASK_SUCCESS",
    GET_TASK_FAILURE: "GET_TASK_FAILURE",
    ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
    UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
    DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
    DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    ADD_TASK_FAILURE: "ADD_TASK_FAILURE",
    GET_TASK_CATEGORY_REQUEST: "GET_TASK_CATEGORY_REQUEST",
    GET_TASK_CATEGORY_SUCCESS: "GET_TASK_CATEGORY_SUCCESS",
    GET_TASK_CATEGORY_FAILURE: "GET_TASK_CATEGORY_FAILURE",
    GET_TASK_SUBCATEGORY_REQUEST: "GET_TASK_SUBCATEGORY_REQUEST",
    GET_TASK_SUBCATEGORY_SUCCESS: "GET_TASK_SUBCATEGORY_SUCCESS",
    GET_TASK_SUBCATEGORY_FAILURE: "GET_TASK_SUBCATEGORY_FAILURE",
  },
  USER: {
    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",

    GET_USERS_REQUEST: "GET_USERS_REQUEST",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",

    CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

    UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

    DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

    SELECT_USER: "SELECT_USER",
    SELECT_ALL_USERS: "SELECT_ALL_USERS",
    CLEAR_SELECTED_USERS: "CLEAR_SELECTED_USERS",

    GET_USERS_ACTIVITY_LOG_REQUEST: "GET_USERS_ACTIVITY_LOG_REQUEST",
    GET_USERS_ACTIVITY_LOG_SUCCESS: "GET_USERS_ACTIVITY_LOG_SUCCESS",
    GET_USERS_ACTIVITY_LOG_FAILURE: "GET_USERS_ACTIVITY_LOG_FAILURE",

    GET_USER_PERMISSION_DETAILS_REQUEST: "GET_USER_PERMISSION_DETAILS_REQUEST",
    GET_USER_PERMISSION_DETAILS_SUCCESS: "GET_USER_PERMISSION_DETAILS_SUCCESS",
    GET_USER_PERMISSION_DETAILS_FAILURE: "GET_USER_PERMISSION_DETAILS_FAILURE",

    
    DELETE_USER_PERMISSION_DETAIL_REQUEST: "DELETE_USER_PERMISSION_DETAIL_REQUEST",
    DELETE_USER_PERMISSION_DETAIL_SUCCESS: "DELETE_USER_PERMISSION_DETAIL_SUCCESS",
    DELETE_USER_PERMISSION_DETAIL_FAILURE: "DELETE_USER_PERMISSION_DETAIL_FAILURE",

    
    ASSIGN_USER_PERMISSIONS_REQUEST: "ASSIGN_USER_PERMISSIONS_REQUEST",
    ASSIGN_USER_PERMISSIONS_SUCCESS: "ASSIGN_USER_PERMISSIONS_SUCCESS",
    ASSIGN_USER_PERMISSIONS_FAILURE: "ASSIGN_USER_PERMISSIONS_FAILURE",

    FETCH_GLOBAL_PERMISSIONS_REQUEST: "FETCH_GLOBAL_PERMISSIONS_REQUEST",
    FETCH_GLOBAL_PERMISSIONS_SUCCESS: "FETCH_GLOBAL_PERMISSIONS_SUCCESS",
    FETCH_GLOBAL_PERMISSIONS_FAILURE: "FETCH_GLOBAL_PERMISSIONS_FAILURE",
  },
  AUDIT: {
    GET_AUTH_AUDIT_LOG_REQUEST: "GET_AUTH_AUDIT_LOG_REQUEST",
    GET_AUTH_AUDIT_LOG_SUCCESS: "GET_AUTH_AUDIT_LOG_SUCCESS",
    GET_AUTH_AUDIT_LOG_FAILURE: "GET_AUTH_AUDIT_LOG_FAILURE",
  },
};

interface AgentManagementActionTypes {
  // START AGENT
  START_AGENT_SERVICE: string;
  REQUEST_START_AGENT_SERVICE: string;
  SUCCESS_START_AGENT_SERVICE: string;
  FAILURE_START_AGENT_SERVICE: string;

  // HEALTH CHECKUP
  FETCH_HEALTH_CHECKUP: string;
  REQUEST_FETCH_HEALTH_CHECKUP: string;
  SUCCESS_FETCH_HEALTH_CHECKUP: string;
  FAILURE_FETCH_HEALTH_CHECKUP: string;

  // RUN HEALTHCHECK
  FETCH_HEALTH_CHECK_RUN: string;
  REQUEST_FETCH_HEALTH_CHECK_RUN: string;
  SUCCESS_FETCH_HEALTH_CHECK_RUN: string;
  FAILURE_FETCH_HEALTH_CHECK_RUN: string;

  // HEALTH CHECKUP BY PORT
  FETCH_HEALTH_CHECKUP_BY_PORT: string;
  REQUEST_FETCH_HEALTH_CHECKUP_BY_PORT: string;
  SUCCESS_FETCH_HEALTH_CHECKUP_BY_PORT: string;
  FAILURE_FETCH_HEALTH_CHECKUP_BY_PORT: string;

  // STOP AGENT
  STOP_AGENT_SERVICE: string;
  REQUEST_STOP_AGENT_SERVICE: string;
  SUCCESS_STOP_AGENT_SERVICE: string;
  FAILURE_STOP_AGENT_SERVICE: string;

  // RESTART Job
  RESTART_JOB_SERVICE: string;
  REQUEST_RESTART_JOB_SERVICE: string;
  SUCCESS_RESTART_JOB_SERVICE: string;
  FAILURE_RESTART_JOB_SERVICE: string;

  // RESTART AGENT
  RESTART_AGENT_SERVICE: string;
  REQUEST_RESTART_AGENT_SERVICE: string;
  SUCCESS_RESTART_AGENT_SERVICE: string;
  FAILURE_RESTART_AGENT_SERVICE: string;

  // SHUTDOWN AGENT
  SHUTDOWN_AGENT_SERVICE: string;
  REQUEST_SHUTDOWN_AGENT_SERVICE: string;
  SUCCESS_SHUTDOWN_AGENT_SERVICE: string;
  FAILURE_SHUTDOWN_AGENT_SERVICE: string;

  // Start AGENT VIA SSH
  STARTSSH_AGENT_SERVICE: string;
  REQUEST_STARTSSH_AGENT_SERVICE: string;
  SUCCESS_STARTSSH_AGENT_SERVICE: string;
  FAILURE_STARTSSH_AGENT_SERVICE: string;

  // CREATE AGENT PROPERTY
  SAVE_AGENT_PROPERTY: string;
  REQUEST_SAVE_AGENT_PROPERTY: string;
  SUCCESS_SAVE_AGENT_PROPERTY: string;
  FAILURE_SAVE_AGENT_PROPERTY: string;

  // UPDATE AGENT PROPERTY
  UPDATE_AGENT_PROPERTY: string;
  REQUEST_UPDATE_AGENT_PROPERTY: string;
  SUCCESS_UPDATE_AGENT_PROPERTY: string;
  FAILURE_UPDATE_AGENT_PROPERTY: string;

  // AGENT BUILD INFO
  FETCH_AGENT_BUILD_INFO: string;
  REQUEST_FETCH_AGENT_BUILD_INFO: string;
  SUCCESS_FETCH_AGENT_BUILD_INFO: string;
  FAILURE_FETCH_AGENT_BUILD_INFO: string;

  // SAVE GLOBAL CONFIGS
  SAVE_GLOBAL_CONFIG: string;
  REQUEST_SAVE_GLOBAL_CONFIG: string;
  SUCCESS_SAVE_GLOBAL_CONFIG: string;
  FAILURE_SAVE_GLOBAL_CONFIG: string;

  // FETCH GLOBAL CONFIGS
  FETCH_GLOBAL_CONFIG: string;
  REQUEST_FETCH_GLOBAL_CONFIG: string;
  SUCCESS_FETCH_GLOBAL_CONFIG: string;
  FAILURE_FETCH_GLOBAL_CONFIG: string;

  // FETCH AGENT SERVICE
  FETCH_AGENT_MANAGEMENT_SERVICE: string;
  REQUEST_FETCH_AGENT_MANAGEMENT_SERVICE: string;
  SUCCESS_FETCH_AGENT_MANAGEMENT_SERVICE: string;
  FAILURE_FETCH_AGENT_MANAGEMENT_SERVICE: string;

  // FETCH AGENT FILTER
  FETCH_AGENT_FILTER: string;
  REQUEST_FETCH_AGENT_FILTER: string;
  SUCCESS_FETCH_AGENT_FILTER: string;
  FAILURE_FETCH_AGENT_FILTER: string;

  // FETCH AGENT FILTER REPOSITORIES
  FETCH_AGENT_REPOSITORIES: string;
  REQUEST_FETCH_AGENT_REPOSITORIES: string;
  SUCCESS_FETCH_AGENT_REPOSITORIES: string;
  FAILURE_FETCH_AGENT_REPOSITORIES: string;

  // ADD AGENT
  ADD_AGENT: string;
  REQUEST_ADD_AGENT: string;
  SUCCESS_ADD_AGENT: string;
  FAILURE_ADD_AGENT: string;

  // GET AGENT LOGS
  FETCH_AGENT_LOGS: string;
  REQUEST_FETCH_AGENT_LOGS: string;
  SUCCESS_FETCH_AGENT_LOGS: string;
  FAILURE_FETCH_AGENT_LOGS: string;

  // GET RELOAD AGENT LOGS
  RELOAD_FETCH_AGENT_LOGS: string;

  // LOCAL CONFIGS
  SAVE_LOCAL_CONFIGS: string;
  REQUEST_SAVE_LOCAL_CONFIGS: string;
  SUCCESS_SAVE_LOCAL_CONFIGS: string;
  FAILURE_SAVE_LOCAL_CONFIGS: string;

  FETCH_LOCAL_CONFIGS: string;
  REQUEST_FETCH_LOCAL_CONFIGS: string;
  SUCCESS_FETCH_LOCAL_CONFIGS: string;
  FAILURE_FETCH_LOCAL_CONFIGS: string;

  // REPOSITORIES
  FETCH_REPOSITORIES: string;
  REQUEST_FETCH_REPOSITORIES: string;
  SUCCESS_FETCH_REPOSITORIES: string;
  FAILURE_FETCH_REPOSITORIES: string;

  DOWNLOAD_REPOSITORIES: string;
  REQUEST_DOWNLOAD_REPOSITORIES: string;
  SUCCESS_DOWNLOAD_REPOSITORIES: string;
  FAILURE_DOWNLOAD_REPOSITORIES: string;

  // SCHEDULER
  SAVE_SCHEDULER_COMMAND: string;
  REQUEST_SAVE_SCHEDULER_COMMAND: string;
  SUCCESS_SAVE_SCHEDULER_COMMAND: string;
  FAILURE_SAVE_SCHEDULER_COMMAND: string;

  UPDATE_SCHEDULER_COMMAND: string;
  REQUEST_UPDATE_SCHEDULER_COMMAND: string;
  SUCCESS_UPDATE_SCHEDULER_COMMAND: string;
  FAILURE_UPDATE_SCHEDULER_COMMAND: string;

  DELETE_SCHEDULER_COMMAND: string;
  REQUEST_DELETE_SCHEDULER_COMMAND: string;
  SUCCESS_DELETE_SCHEDULER_COMMAND: string;
  FAILURE_DELETE_SCHEDULER_COMMAND: string;

  LIST_SCHEDULER_COMMAND: string;
  REQUEST_LIST_SCHEDULER_COMMAND: string;
  SUCCESS_LIST_SCHEDULER_COMMAND: string;
  FAILURE_LIST_SCHEDULER_COMMAND: string;

  FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: string;
  REQUEST_FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: string;
  SUCCESS_FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: string;
  FAILURE_FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: string;

  // AGENT DISCOVERY SYNUP
  SYNCUP_AGENT_DISCOVERY: string;
  REQUEST_SYNCUP_AGENT_DISCOVERY: string;
  SUCCESS_SYNCUP_AGENT_DISCOVERY: string;
  FAILURE_SYNCUP_AGENT_DISCOVERY: string;

  // FETCH AGENT METRICS
  FETCH_AGENT_METRICS: string;
  REQUEST_FETCH_AGENT_METRICS: string;
  SUCCESS_FETCH_AGENT_METRICS: string;
  FAILURE_FETCH_AGENT_METRICS: string;

  // Sync Scripts
  SYNC_SCRIPTS: string;
  REQUEST_SYNC_SCRIPTS: string;
  SUCCESS_SYNC_SCRIPTS: string;
  FAILURE_SYNC_SCRIPTS: string;

  // FETCH AGENT REGEION
  FETCH_AGENT_REGIONS: string;
  REQUEST_FETCH_AGENT_REGIONS: string;
  SUCCESS_FETCH_AGENT_REGIONS: string;
  FAILURE_FETCH_AGENT_REGIONS: string;

  // FETCH AGENT PLATFORM
  FETCH_AGENT_PLATFORMS: string;
  REQUEST_FETCH_AGENT_PLATFORMS: string;
  SUCCESS_FETCH_AGENT_PLATFORMS: string;
  FAILURE_FETCH_AGENT_PLATFORMS: string;

  // FETCH AGENT ENVIRONMENT
  FETCH_AGENT_ENVIRONMENTS: string;
  REQUEST_FETCH_AGENT_ENVIRONMENTS: string;
  SUCCESS_FETCH_AGENT_ENVIRONMENTS: string;
  FAILURE_FETCH_AGENT_ENVIRONMENTS: string;

  // FETCH AGENT METRICS TILES DATA
  FETCH_METRICS_TILES_DATA: string;
  REQUEST_FETCH_METRICS_TILES_DATA: string;
  SUCCESS_FETCH_METRICS_TILES_DATA: string;
  FAILURE_FETCH_METRICS_TILES_DATA: string;

  // FETCH AGENT SID
  FETCH_AGENT_SIDS: string;
  REQUEST_FETCH_AGENT_SIDS: string;
  SUCCESS_FETCH_AGENT_SIDS: string;
  FAILURE_FETCH_AGENT_SIDS: string;

  // FETCH AGENT OS
  FETCH_AGENT_OS_TYPES: string;
  REQUEST_FETCH_AGENT_OS_TYPES: string;
  SUCCESS_FETCH_AGENT_OS_TYPES: string;
  FAILURE_FETCH_AGENT_OS_TYPES: string;

  // FETCH AGENT SERVICE_NAME
  FETCH_AGENT_SERVICE_NAMES: string;
  REQUEST_FETCH_AGENT_SERVICE_NAMES: string;
  SUCCESS_FETCH_AGENT_SERVICE_NAMES: string;
  FAILURE_FETCH_AGENT_SERVICE_NAMES: string;

  // FETCH AGENT VERSION
  FETCH_AGENT_VERSIONS: string;
  REQUEST_FETCH_AGENT_VERSIONS: string;
  SUCCESS_FETCH_AGENT_VERSIONS: string;
  FAILURE_FETCH_AGENT_VERSIONS: string;

  // FORCE UPDATE DATA AGENT
  SYNC_AGENT_HEALTH_CONFIGS: string;
  REQUEST_SYNC_AGENT_HEALTH_CONFIGS: string;
  SUCCESS_SYNC_AGENT_HEALTH_CONFIGS: string;
  FAILURE_SYNC_AGENT_HEALTH_CONFIGS: string;

  // START SELECTED AGENTS
  START_SELECTED_AGENT_SERVICE: string;
  REQUEST_SELECTED_START_AGENT_SERVICE: string;
  SUCCESS_SELECTED_START_AGENT_SERVICE: string;
  FAILURE_SELECTED_START_AGENT_SERVICE: string;

  // STOP SELECTED AGENTS
  STOP_SELECTED_AGENT_SERVICE: string;
  REQUEST_SELECTED_STOP_AGENT_SERVICE: string;
  SUCCESS_SELECTED_STOP_AGENT_SERVICE: string;
  FAILURE_SELECTED_STOP_AGENT_SERVICE: string;

  // RESTART SELECTED AGENTS
  RESTART_SELECTED_AGENT_SERVICE: string;
  REQUEST_SELECTED_RESTART_AGENT_SERVICE: string;
  SUCCESS_SELECTED_RESTART_AGENT_SERVICE: string;
  FAILURE_SELECTED_RESTART_AGENT_SERVICE: string;

  // HEALTH CHECKUP SELECTED AGENTS
  HEALTHCHECKUP_SELECTED_AGENT_SERVICE: string;
  REQUEST_SELECTED_HEALTHCHECKUP_AGENT_SERVICE: string;
  SUCCESS_SELECTED_HEALTHCHECKUP_AGENT_SERVICE: string;
  FAILURE_SELECTED_HEALTHCHECKUP_AGENT_SERVICE: string;

  // UPGRADE AGENTS FOR SELECTED AGENTS
  UPGRADE_SELECTED_AGENTS: string;
  REQUEST_UPGRADE_SELECTED_AGENTS: string;
  SUCCESS_UPGRADE_SELECTED_AGENTS: string;
  FAILURE_UPGRADE_SELECTED_AGENTS: string;

  // UPGRADE AGENTS
  FETCH_UPGRADE_AGENTS: string;
  REQUEST_FETCH_UPGRADE_AGENTS: string;
  SUCCESS_FETCH_UPGRADE_AGENTS: string;
  FAILURE_FETCH_UPGRADE_AGENTS: string;

  // FETCH AGENT MASTERDATA
  FETCH_AGENT_MASTERDATA: string;
  REQUEST_FETCH_AGENT_MASTERDATA: string;
  SUCCESS_FETCH_AGENT_MASTERDATA: string;
  FAILURE_FETCH_AGENT_MASTERDATA: string;

  // ADD AGENT MASTERDATA
  ADD_AGENT_MASTERDATA: string;
  REQUEST_ADD_AGENT_MASTERDATA: string;
  SUCCESS_ADD_AGENT_MASTERDATA: string;
  FAILURE_ADD_AGENT_MASTERDATA: string;

  // DELETE HOSTNAME
  DELETE_HOSTNAME: string;
  REQUEST_DELETE_HOSTNAME: string;
  SUCCESS_DELETE_HOSTNAME: string;
  FAILURE_DELETE_HOSTNAME: string;

  // AGENT  INFO
  FETCH_AGENT_INFO: string;
  REQUEST_FETCH_AGENT_INFO: string;
  SUCCESS_FETCH_AGENT_INFO: string;
  FAILURE_FETCH_AGENT_INFO: string;

  // VERSION MANAGEMENT
  FETCH_VERSIONS: string;
  REQUEST_FETCH_VERSIONS: string;
  SUCCESS_FETCH_VERSIONS: string;
  FAILURE_FETCH_VERSIONS: string;

  // Add these new actions
  CREATE_VERSION: string;
  REQUEST_CREATE_VERSION: string;
  SUCCESS_CREATE_VERSION: string;
  FAILURE_CREATE_VERSION: string;

  // Update these new actions
  UPDATE_VERSION: string;
  REQUEST_UPDATE_VERSION: string;
  SUCCESS_UPDATE_VERSION: string;
  FAILURE_UPDATE_VERSION: string;

  // Delete these new actions
  DELETE_VERSION: string;
  REQUEST_DELETE_VERSION: string;
  SUCCESS_DELETE_VERSION: string;
  FAILURE_DELETE_VERSION: string;

  // Manual sync versions
  MANUAL_SYNC_VERSIONS: string;
  REQUEST_MANUAL_SYNC_VERSIONS: string;
  SUCCESS_MANUAL_SYNC_VERSIONS: string;
  FAILURE_MANUAL_SYNC_VERSIONS: string;
}

export const AGENT_MANAGEMENT: AgentManagementActionTypes = {
  // START AGENT
  START_AGENT_SERVICE: "startAgentService",
  REQUEST_START_AGENT_SERVICE: "requestStartAgentService",
  SUCCESS_START_AGENT_SERVICE: "successStartAgentService",
  FAILURE_START_AGENT_SERVICE: "failureStartAgentService",

  // HEALTH CHECKUP
  FETCH_HEALTH_CHECKUP: "fetchHealthCheckup",
  REQUEST_FETCH_HEALTH_CHECKUP: "requestFetchHealthCheckup",
  SUCCESS_FETCH_HEALTH_CHECKUP: "successFetchHealthCheckup",
  FAILURE_FETCH_HEALTH_CHECKUP: "failureFetchHealthCheckup",

  // RUN HEALTHCHECK
  FETCH_HEALTH_CHECK_RUN: "fetchHealthCheckRun",
  REQUEST_FETCH_HEALTH_CHECK_RUN: "requestFetchHealthCheckRun",
  SUCCESS_FETCH_HEALTH_CHECK_RUN: "successFetchHealthCheckRun",
  FAILURE_FETCH_HEALTH_CHECK_RUN: "failureFetchHealthCheckRun",

  // HEALTH CHECKUP BY PORT
  FETCH_HEALTH_CHECKUP_BY_PORT: "fetchHealthCheckupByPort",
  REQUEST_FETCH_HEALTH_CHECKUP_BY_PORT: "requestFetchHealthCheckupByPort",
  SUCCESS_FETCH_HEALTH_CHECKUP_BY_PORT: "successFetchHealthCheckupByPort",
  FAILURE_FETCH_HEALTH_CHECKUP_BY_PORT: "failureFetchHealthCheckupByPort",

  // STOP AGENT
  STOP_AGENT_SERVICE: "stopAgentService",
  REQUEST_STOP_AGENT_SERVICE: "requestStopAgentService",
  SUCCESS_STOP_AGENT_SERVICE: "successStopAgentService",
  FAILURE_STOP_AGENT_SERVICE: "failureStopAgentService",

  // RESTART Job
  RESTART_JOB_SERVICE: "restartJobService",
  REQUEST_RESTART_JOB_SERVICE: "requestRestartJobService",
  SUCCESS_RESTART_JOB_SERVICE: "successRestartJobService",
  FAILURE_RESTART_JOB_SERVICE: "failureRestartJobService",

  // RESTART AGENT
  RESTART_AGENT_SERVICE: "restartAgentService",
  REQUEST_RESTART_AGENT_SERVICE: "requestRestartAgentService",
  SUCCESS_RESTART_AGENT_SERVICE: "successRestartAgentService",
  FAILURE_RESTART_AGENT_SERVICE: "failureRestartAgentService",

  // SHUTDOWN AGENT
  SHUTDOWN_AGENT_SERVICE: "shutDownAgentService",
  REQUEST_SHUTDOWN_AGENT_SERVICE: "requestShutDownAgentService",
  SUCCESS_SHUTDOWN_AGENT_SERVICE: "successShutDownAgentService",
  FAILURE_SHUTDOWN_AGENT_SERVICE: "failureShutDownAgentService",

  // Start AGENT VIA SSH
  STARTSSH_AGENT_SERVICE: "startSSHAgentService",
  REQUEST_STARTSSH_AGENT_SERVICE: "requestStartSSHAgentService",
  SUCCESS_STARTSSH_AGENT_SERVICE: "successStartSSHAgentService",
  FAILURE_STARTSSH_AGENT_SERVICE: "failureStartSSHAgentService",

  // CREATE AGENT PROPERTY
  SAVE_AGENT_PROPERTY: "saveAgentProperty",
  REQUEST_SAVE_AGENT_PROPERTY: "requestSaveAgentProperty",
  SUCCESS_SAVE_AGENT_PROPERTY: "successSaveAgentProperty",
  FAILURE_SAVE_AGENT_PROPERTY: "failureSaveAgentProperty",

  // UPDATE AGENT PROPERTY
  UPDATE_AGENT_PROPERTY: "updateAgentProperty",
  REQUEST_UPDATE_AGENT_PROPERTY: "requestUpdateAgentProperty",
  SUCCESS_UPDATE_AGENT_PROPERTY: "successUpdateAgentProperty",
  FAILURE_UPDATE_AGENT_PROPERTY: "failureUpdateAgentProperty",

  // AGENT BUILD INFO
  FETCH_AGENT_BUILD_INFO: "fetchAgentBuildInfo",
  REQUEST_FETCH_AGENT_BUILD_INFO: "requestFetchAgentBuildInfo",
  SUCCESS_FETCH_AGENT_BUILD_INFO: "successFetchAgentBuildInfo",
  FAILURE_FETCH_AGENT_BUILD_INFO: "failureFetchAgentBuildInfo",

  // SAVE GLOBAL CONFIGS
  SAVE_GLOBAL_CONFIG: "saveGlobalConfig",
  REQUEST_SAVE_GLOBAL_CONFIG: "requestSaveGlobalConfig",
  SUCCESS_SAVE_GLOBAL_CONFIG: "successSaveGlobalConfig",
  FAILURE_SAVE_GLOBAL_CONFIG: "failureSaveGlobalConfig",

  // FETCH GLOBAL CONFIGS
  FETCH_GLOBAL_CONFIG: "fetchGlobalConfig",
  REQUEST_FETCH_GLOBAL_CONFIG: "requestFetchGlobalConfig",
  SUCCESS_FETCH_GLOBAL_CONFIG: "successFetchGlobalConfig",
  FAILURE_FETCH_GLOBAL_CONFIG: "failureFetchGlobalConfig",

  // FETCH AGENT SERVICE
  FETCH_AGENT_MANAGEMENT_SERVICE: "fetchAgentManageMentService",
  REQUEST_FETCH_AGENT_MANAGEMENT_SERVICE: "requestFetchAgentManageMentService",
  SUCCESS_FETCH_AGENT_MANAGEMENT_SERVICE: "successFetchAgentManageMentService",
  FAILURE_FETCH_AGENT_MANAGEMENT_SERVICE: "failureFetchAgentManageMentService",

  // FETCH AGENT FILTER
  FETCH_AGENT_FILTER: "fetchAgentFilter",
  REQUEST_FETCH_AGENT_FILTER: "requestFetchAgentFilter",
  SUCCESS_FETCH_AGENT_FILTER: "successFetchAgentFilter",
  FAILURE_FETCH_AGENT_FILTER: "failureFetchAgentFilter",

  // FETCH AGENT FILTER REPOSITORIES
  FETCH_AGENT_REPOSITORIES: "fetchAgentRepositories",
  REQUEST_FETCH_AGENT_REPOSITORIES: "requestFetchAgentRepositories",
  SUCCESS_FETCH_AGENT_REPOSITORIES: "successFetchAgentRepositories",
  FAILURE_FETCH_AGENT_REPOSITORIES: "failureFetchAgentRepositories",

  // ADD AGENT
  ADD_AGENT: "addAgent",
  REQUEST_ADD_AGENT: "requestAddAgent",
  SUCCESS_ADD_AGENT: "successAddAgent",
  FAILURE_ADD_AGENT: "failureAddAgent",

  // GET AGENT LOGS
  FETCH_AGENT_LOGS: "fetchAgentLogs",
  REQUEST_FETCH_AGENT_LOGS: "requestFetchAgentLogs",
  SUCCESS_FETCH_AGENT_LOGS: "successFetchAgentLogs",
  FAILURE_FETCH_AGENT_LOGS: "failureFetchAgentLogs",

  // GET RELOAD AGENT LOGS
  RELOAD_FETCH_AGENT_LOGS: "reloadFetchAgentLogs",

  // LOCAL CONFIGS
  SAVE_LOCAL_CONFIGS: "saveLocalConfigs",
  REQUEST_SAVE_LOCAL_CONFIGS: "requestSaveLocalConfigs",
  SUCCESS_SAVE_LOCAL_CONFIGS: "successSaveLocalConfigs",
  FAILURE_SAVE_LOCAL_CONFIGS: "failureSaveLocalConfigs",

  FETCH_LOCAL_CONFIGS: "fetchLocalConfigs",
  REQUEST_FETCH_LOCAL_CONFIGS: "requestFetchLocalConfigs",
  SUCCESS_FETCH_LOCAL_CONFIGS: "successFetchLocalConfigs",
  FAILURE_FETCH_LOCAL_CONFIGS: "failureFetchLocalConfigs",

  // REPOSITORIES
  FETCH_REPOSITORIES: "fetchRespositories",
  REQUEST_FETCH_REPOSITORIES: "requestFetchRespositories",
  SUCCESS_FETCH_REPOSITORIES: "successFetchRespositories",
  FAILURE_FETCH_REPOSITORIES: "failureFetchRespositories",

  DOWNLOAD_REPOSITORIES: "downloadRepositories",
  REQUEST_DOWNLOAD_REPOSITORIES: "requestDownloadRepositories",
  SUCCESS_DOWNLOAD_REPOSITORIES: "successDownloadRepositories",
  FAILURE_DOWNLOAD_REPOSITORIES: "failureDownloadRepositories",

  // SCHEDULER
  SAVE_SCHEDULER_COMMAND: "saveSchedulerCommand",
  REQUEST_SAVE_SCHEDULER_COMMAND: "requestSaveSchedulerCommand",
  SUCCESS_SAVE_SCHEDULER_COMMAND: "successSaveSchedulerCommand",
  FAILURE_SAVE_SCHEDULER_COMMAND: "failureSaveSchedulerCommand",

  UPDATE_SCHEDULER_COMMAND: "updateSchedulerCommand",
  REQUEST_UPDATE_SCHEDULER_COMMAND: "requestUpdateSchedulerCommand",
  SUCCESS_UPDATE_SCHEDULER_COMMAND: "successUpdateSchedulerCommand",
  FAILURE_UPDATE_SCHEDULER_COMMAND: "failureUpdateSchedulerCommand",

  DELETE_SCHEDULER_COMMAND: "deleteSchedulerCommand",
  REQUEST_DELETE_SCHEDULER_COMMAND: "requestDeleteSchedulerCommand",
  SUCCESS_DELETE_SCHEDULER_COMMAND: "successDeleteSchedulerCommand",
  FAILURE_DELETE_SCHEDULER_COMMAND: "failureDeleteSchedulerCommand",

  LIST_SCHEDULER_COMMAND: "listSchedulerCommand",
  REQUEST_LIST_SCHEDULER_COMMAND: "requestListSchedulerCommand",
  SUCCESS_LIST_SCHEDULER_COMMAND: "successListSchedulerCommand",
  FAILURE_LIST_SCHEDULER_COMMAND: "failureListSchedulerCommand",

  FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: "fetchScheduledJobsByCommandId",
  REQUEST_FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: "RequestFetchScheduledJobsByCommandId",
  SUCCESS_FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: "successFetchScheduledJobsByCommandId",
  FAILURE_FETCH_SCHEDULED_JOBS_BY_COMMAND_ID: "failureFetchScheduledJobsByCommandId",

  // AGENT DISCOVERY SYNUP
  SYNCUP_AGENT_DISCOVERY: "syncupAgentDiscovery",
  REQUEST_SYNCUP_AGENT_DISCOVERY: "requestSyncupAgentDiscovery",
  SUCCESS_SYNCUP_AGENT_DISCOVERY: "successSyncupAgentDiscovery",
  FAILURE_SYNCUP_AGENT_DISCOVERY: "failureSyncupAgentDiscovery",

  // FETCH AGENT METRICS
  FETCH_AGENT_METRICS: "fetchAgentMetrics",
  REQUEST_FETCH_AGENT_METRICS: "requestFetchAgentMetrics",
  SUCCESS_FETCH_AGENT_METRICS: "successFetchAgentMetrics",
  FAILURE_FETCH_AGENT_METRICS: "failureFetchAgentMetrics",

  // Sync Scripts
  SYNC_SCRIPTS: "syncScripts",
  REQUEST_SYNC_SCRIPTS: "requestSyncScripts",
  SUCCESS_SYNC_SCRIPTS: "successSyncScripts",
  FAILURE_SYNC_SCRIPTS: "failureSyncScripts",

  // FETCH AGENT REGEION
  FETCH_AGENT_REGIONS: "fetchAgentRegions",
  REQUEST_FETCH_AGENT_REGIONS: "requestFetchAgentRegions",
  SUCCESS_FETCH_AGENT_REGIONS: "successFetchAgentRegions",
  FAILURE_FETCH_AGENT_REGIONS: "failureFetchAgentRegions",

  // FETCH AGENT PLATFORM
  FETCH_AGENT_PLATFORMS: "fetchAgentPlatforms",
  REQUEST_FETCH_AGENT_PLATFORMS: "requestFetchAgentPlatforms",
  SUCCESS_FETCH_AGENT_PLATFORMS: "successFetchAgentPlatforms",
  FAILURE_FETCH_AGENT_PLATFORMS: "failureFetchAgentPlatforms",

  // FETCH AGENT ENVIRONMENT
  FETCH_AGENT_ENVIRONMENTS: "fetchAgentEnvironments",
  REQUEST_FETCH_AGENT_ENVIRONMENTS: "requestFetchAgentEnvironments",
  SUCCESS_FETCH_AGENT_ENVIRONMENTS: "successFetchAgentEnvironments",
  FAILURE_FETCH_AGENT_ENVIRONMENTS: "failureFetchAgentEnvironments",

  // FETCH AGENT METRICS TILES DATA
  FETCH_METRICS_TILES_DATA: "fetchMetricsTilesData",
  REQUEST_FETCH_METRICS_TILES_DATA: "requestFetchMetricsTilesData",
  SUCCESS_FETCH_METRICS_TILES_DATA: "successFetchMetricsTilesData",
  FAILURE_FETCH_METRICS_TILES_DATA: "failureFetchMetricsTilesData",

  // FETCH AGENT SID
  FETCH_AGENT_SIDS: "fetchAgentSids",
  REQUEST_FETCH_AGENT_SIDS: "requestFetchAgentSids",
  SUCCESS_FETCH_AGENT_SIDS: "successFetchAgentSids",
  FAILURE_FETCH_AGENT_SIDS: "failureFetchAgentSids",

  // FETCH AGENT OS
  FETCH_AGENT_OS_TYPES: "fetchAgentOsTypes",
  REQUEST_FETCH_AGENT_OS_TYPES: "requestFetchAgentOsTypes",
  SUCCESS_FETCH_AGENT_OS_TYPES: "successFetchAgentOsTypes",
  FAILURE_FETCH_AGENT_OS_TYPES: "failureFetchAgentOsTypes",

  // FETCH AGENT SERVICE_NAME
  FETCH_AGENT_SERVICE_NAMES: "fetchAgentServiceNames",
  REQUEST_FETCH_AGENT_SERVICE_NAMES: "requestFetchAgentServiceNames",
  SUCCESS_FETCH_AGENT_SERVICE_NAMES: "successFetchAgentServiceNames",
  FAILURE_FETCH_AGENT_SERVICE_NAMES: "failureFetchAgentServiceNames",

  // FETCH AGENT VERSION
  FETCH_AGENT_VERSIONS: "fetchAgentVersions",
  REQUEST_FETCH_AGENT_VERSIONS: "requestFetchAgentVersions",
  SUCCESS_FETCH_AGENT_VERSIONS: "successFetchAgentVersions",
  FAILURE_FETCH_AGENT_VERSIONS: "failureFetchAgentVersions",

  // FORCE UPDATE DATA AGENT
  SYNC_AGENT_HEALTH_CONFIGS: "syncAgentHealthConfigs",
  REQUEST_SYNC_AGENT_HEALTH_CONFIGS: "requestSyncAgentHealthConfigs",
  SUCCESS_SYNC_AGENT_HEALTH_CONFIGS: "successSyncAgentHealthConfigs",
  FAILURE_SYNC_AGENT_HEALTH_CONFIGS: "failureSyncAgentHealthConfigs",

  // START SELECTED AGENTS
  START_SELECTED_AGENT_SERVICE: "startSelectedAgentService",
  REQUEST_SELECTED_START_AGENT_SERVICE: "requestStartSelectedAgentService",
  SUCCESS_SELECTED_START_AGENT_SERVICE: "successStartSelectedAgentService",
  FAILURE_SELECTED_START_AGENT_SERVICE: "failureStartSelectedAgentService",

  // STOP SELECTED AGENTS
  STOP_SELECTED_AGENT_SERVICE: "stopSelectedAgentService",
  REQUEST_SELECTED_STOP_AGENT_SERVICE: "requestStopSelectedAgentService",
  SUCCESS_SELECTED_STOP_AGENT_SERVICE: "successStoptSelectedAgentService",
  FAILURE_SELECTED_STOP_AGENT_SERVICE: "failureStopSelectedAgentService",

  // RESTART SELECTED AGENTS
  RESTART_SELECTED_AGENT_SERVICE: "restartSelectedAgentService",
  REQUEST_SELECTED_RESTART_AGENT_SERVICE: "requestRestartSelectedAgentService",
  SUCCESS_SELECTED_RESTART_AGENT_SERVICE: "successRestartSelectedAgentService",
  FAILURE_SELECTED_RESTART_AGENT_SERVICE: "failureRestartSelectedAgentService",

  // HEALTH CHECKUP SELECTED AGENTS
  HEALTHCHECKUP_SELECTED_AGENT_SERVICE: "healthCheckupSelectedAgentService",
  REQUEST_SELECTED_HEALTHCHECKUP_AGENT_SERVICE: "requestHealthCheckupSelectedAgentService",
  SUCCESS_SELECTED_HEALTHCHECKUP_AGENT_SERVICE: "successHealthCheckuptSelectedAgentService",
  FAILURE_SELECTED_HEALTHCHECKUP_AGENT_SERVICE: "failureHealthCheckupSelectedAgentService",

  // UPGRADE AGENTS FOR SELECTED AGENTS
  UPGRADE_SELECTED_AGENTS: "upgradeSelectedAgents",
  REQUEST_UPGRADE_SELECTED_AGENTS: "requestUpgradeSelectedAgents",
  SUCCESS_UPGRADE_SELECTED_AGENTS: "successUpgradeSelectedAgents",
  FAILURE_UPGRADE_SELECTED_AGENTS: "failureUpgradeSelectedAgents",

  // UPGRADE AGENTS
  FETCH_UPGRADE_AGENTS: "fetchUpgradeAgents",
  REQUEST_FETCH_UPGRADE_AGENTS: "requestFetchUpgradeAgents",
  SUCCESS_FETCH_UPGRADE_AGENTS: "successFetchUpgradeAgents",
  FAILURE_FETCH_UPGRADE_AGENTS: "failureFetchUpgradeAgents",

  // FETCH AGENT MASTERDATA
  FETCH_AGENT_MASTERDATA: "fetchAgentMasterdata",
  REQUEST_FETCH_AGENT_MASTERDATA: "requestFetchAgentMasterdata",
  SUCCESS_FETCH_AGENT_MASTERDATA: "successFetchAgentMasterdata",
  FAILURE_FETCH_AGENT_MASTERDATA: "failureFetchAgentMasterdata",

  // ADD AGENT MASTERDATA
  ADD_AGENT_MASTERDATA: "addAgentMasterdata",
  REQUEST_ADD_AGENT_MASTERDATA: "requestAddAgentMasterdata",
  SUCCESS_ADD_AGENT_MASTERDATA: "successAddAgentMasterdata",
  FAILURE_ADD_AGENT_MASTERDATA: "failureAddAgentMasterdata",

  // DELETE HOSTNAME
  DELETE_HOSTNAME: "deleteHostname",
  REQUEST_DELETE_HOSTNAME: "requestDeleteHostname",
  SUCCESS_DELETE_HOSTNAME: "successDeleteHostname",
  FAILURE_DELETE_HOSTNAME: "failureDeleteHostname",

  // AGENT  INFO
  FETCH_AGENT_INFO: "fetchAgentInfo",
  REQUEST_FETCH_AGENT_INFO: "requestFetchAgentInfo",
  SUCCESS_FETCH_AGENT_INFO: "successFetchAgentInfo",
  FAILURE_FETCH_AGENT_INFO: "failureFetchAgentInfo",

  // VERSION MANAGEMENT
  FETCH_VERSIONS: "fetchVersions",
  REQUEST_FETCH_VERSIONS: "requestFetchVersions",
  SUCCESS_FETCH_VERSIONS: "successFetchVersions",
  FAILURE_FETCH_VERSIONS: "failureFetchVersions",

  // Add these new actions
  CREATE_VERSION: "createVersion",
  REQUEST_CREATE_VERSION: "requestCreateVersion",
  SUCCESS_CREATE_VERSION: "successCreateVersion",
  FAILURE_CREATE_VERSION: "failureCreateVersion",

  // Update these new actions
  UPDATE_VERSION: "updateVersion",
  REQUEST_UPDATE_VERSION: "requestUpdateVersion",
  SUCCESS_UPDATE_VERSION: "successUpdateVersion",
  FAILURE_UPDATE_VERSION: "failureUpdateVersion",

  // Delete these new actions
  DELETE_VERSION: "deleteVersion",
  REQUEST_DELETE_VERSION: "requestDeleteVersion",
  SUCCESS_DELETE_VERSION: "successDeleteVersion",
  FAILURE_DELETE_VERSION: "failureDeleteVersion",

  // Manual sync versions
  MANUAL_SYNC_VERSIONS: "manualSyncVersions",
  REQUEST_MANUAL_SYNC_VERSIONS: "requestManualSyncVersions",
  SUCCESS_MANUAL_SYNC_VERSIONS: "successManualSyncVersions",
  FAILURE_MANUAL_SYNC_VERSIONS: "failureManualSyncVersions",
};
