export const SET_APP_READY = "setAppReady";
export const UPDATE_APP_READY = "updateAppReady";

export const LOADING = "rdcrLoading";
export const SEARCH_LOADING = "rdcrSearchLoading";

export const RDCR_UPDATE_SYSTEM_FIELD = "rdcrUpdateSystemField";
export const SAGA_UPDATE_SYSTEM_FORMS = "sagaUpdateSystemForms";
export const RDCR_UPDATE_SYSTEM_FORMS = "rdcrUpdateSystemForms";
export const RDCR_CLEAR_SYSTEM_FORMS = "rdcrClearSystemForms";

export const SAGA_GET_AVAILABLE_RECIPE_TYPES = "sagaGetAvailableRecipeTypes";
export const RDCR_UPDATE_AVAILABLE_RECIPE_TYPES = "rdcrUpdateAvailableRecipeTypes";

export const RDCR_UPDATE_RECIPE_TYPE = "rdcrUpdateRecipeType";
export const SAGA_GET_SYSTEM_FORMS = "sagaGetSystemForms";
export const SAGA_REBUILD_SYSTEM_FORMS = "sagaRebuildSystemForms";
export const SAGA_ADD_ITEM_SYSTEM_FORMS = "sagaAddItemSystemForms";
export const SAGA_REMOVE_ITEM_SYSTEM_FORMS = "sagaRemoveItemSystemForms";
export const SAGA_SUBMIT_SYSTEM_FORMS = "sagaSubmitSystemForms";
export const RDCR_SUBMIT_SYSTEM_FORMS = "rdcrSubmitSystemForms";
export const SAGA_SUBMIT_PRIVATE_KEY = "sagaSubmitPrivateKey";
export const SAGA_GET_PRIVATE_KEY = "sagaGetPrivateKey";
export const SAGA_GET_SYSTEM_STATUSES = "sagaGetSystemStatuses";
export const SAGA_SUBSCRIBE_SYSTEM_DEPLOYMENT = "sagaSubscribeSystemDeployment";
export const SAGA_UNSUBSCRIBE_SYSTEM_DEPLOYMENT = "sagaUnSubscribeSystemDeployment";
export const SAGA_SUBSCRIBE_INSTANCE_LOG = "sagaSubscribeInstanceLog";
export const SAGA_UNSUBSCRIBE_INSTANCE_LOG = "sagaUnSubscribeInstanceLog";
export const LOADING_SYSTEM_INSTANCE_LOG = "rdcrLoadingSystemInstanceLog";
export const RDCR_UPDATE_SYSTEM_INSTANCE_LOG = "rdcrUpdateSystemInstanceLog";
export const RDCR_UPDATE_SYSTEM_CHANNELS = "rdcrUpdateSystemChannels";
export const SAGA_GET_SYSTEM_DEPLOYMENTS = "sagaGetSystemDeployments";
export const SAGA_GET_SYSTEM_DEPLOYMENT = "sagaGetSystemDeployment";
export const RDCR_UPDATE_SYSTEM_DEPLOYMENTS = "rdcrUpdateSystemDeployments";
export const RDCR_UPDATE_SYSTEM_DEPLOYMENT = "rdcrUpdateSystemDeployment";
export const RDCR_UPDATE_SYSTEM_STATUSES = "rdcrUpdateSystemStatuses";
export const RDCR_UPDATE_SYSTEM_ID = "rdcrUpdateSystemId";
export const RDCR_UPDATE_SYSTEM_SEARCH = "rdcrUpdateSystemSearch";
export const SAGA_SYSTEM_SEARCH_DISCOVERY = "sagaSystemSearchDiscovery";

export const SAGA_GET_AVAILABLE_REPOSITORIES = "sagaGetAvailableRepositories";
export const SAGA_GET_AVAILABLE_SYSTEM_SUCCESS = "sagaGetExcludeRepos";
export const RDCR_UPDATE_AVAILABLE_REPOSITORIES = "rdcrUpdateAvailableRepositories";

export const RDCR_UPDATE_SELECTED_REPOSITORY = "rdcrUpdateSelectedRepository";
export const RDCR_UPDATE_SELECTED_APSID = "rdcrUpdateSelectedApsid";
export const RDCR_UPDATE_SELECTED_SID = "rdcrUpdateSelectedSid";


export const ADD_FORM_VALUES = "addFormValues";
export const CLEAR_FORM_VALUES = "clearFormValues";

export const AUTH = {
  GROUP: {
    ADD_GROUP_REQUEST: "ADD_GROUP_REQUEST",
    ADD_GROUP_SUCCESS: "ADD_GROUP_SUCCESS",
    ADD_GROUP_FAILURE: "ADD_GROUP_FAILURE",

    GET_GROUP_REQUEST: "GET_GROUP_REQUEST",
    GET_GROUP_SUCCESS: "GET_GROUP_SUCCESS",
    GET_GROUP_FAILURE: "GET_GROUP_FAILURE",

    UPDATE_GROUP_REQUEST: "UPDATE_GROUP_REQUEST",
    UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",
    UPDATE_GROUP_FAILURE: "UPDATE_GROUP_FAILURE",

    DELETE_GROUP_REQUEST: "DELETE_GROUP_REQUEST",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE",
  },
  PERMISSION: {
    ADD_PERMISSION_REQUEST: "ADD_PERMISSION_REQUEST",
    ADD_PERMISSION_SUCCESS: "ADD_PERMISSION_SUCCESS",
    ADD_PERMISSION_FAILURE: "ADD_PERMISSION_FAILURE",

    GET_PERMISSION_GROUP_REQUEST: "GET_PERMISSION_GROUP_REQUEST",
    GET_PERMISSION_GROUP_SUCCESS: "GET_PERMISSION_GROUP_SUCCESS",
    GET_PERMISSION_GROUP_FAILURE: "GET_PERMISSION_GROUP_FAILURE",
    REFRESH_PERMISSION_COUNTER: "REFRESH_PERMISSION_COUNTER",
  },
  TASK: {
    GET_TASK_REQUEST: "GET_TASK_REQUEST",
    GET_TASK_SUCCESS: "GET_TASK_SUCCESS",
    GET_TASK_FAILURE: "GET_TASK_FAILURE",
    ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
    UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
    DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
    DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    ADD_TASK_FAILURE: "ADD_TASK_FAILURE",
    GET_TASK_CATEGORY_REQUEST: "GET_TASK_CATEGORY_REQUEST",
    GET_TASK_CATEGORY_SUCCESS: "GET_TASK_CATEGORY_SUCCESS",
    GET_TASK_CATEGORY_FAILURE: "GET_TASK_CATEGORY_FAILURE",
    GET_TASK_SUBCATEGORY_REQUEST: "GET_TASK_SUBCATEGORY_REQUEST",
    GET_TASK_SUBCATEGORY_SUCCESS: "GET_TASK_SUBCATEGORY_SUCCESS",
    GET_TASK_SUBCATEGORY_FAILURE: "GET_TASK_SUBCATEGORY_FAILURE",
  },
  USER: {
    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",

    GET_USERS_REQUEST: "GET_USERS_REQUEST",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILURE: "GET_USERS_FAILURE",

    UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

    GET_USERS_ACTIVITY_LOG_REQUEST: "GET_USERS_ACTIVITY_LOG_REQUEST",
    GET_USERS_ACTIVITY_LOG_SUCCESS: "GET_USERS_ACTIVITY_LOG_SUCCESS",
    GET_USERS_ACTIVITY_LOG_FAILURE: "GET_USERS_ACTIVITY_LOG_FAILURE",
  },
  AUDIT: {
    GET_AUTH_AUDIT_LOG_REQUEST: "GET_AUTH_AUDIT_LOG_REQUEST",
    GET_AUTH_AUDIT_LOG_SUCCESS: "GET_AUTH_AUDIT_LOG_SUCCESS",
    GET_AUTH_AUDIT_LOG_FAILURE: "GET_AUTH_AUDIT_LOG_FAILURE",
  },
};

export const BATCH_OPERATION = {
  REQUEST_BATCH_JOB_DETAILS: "REQUEST_BATCH_JOB_DETAILS",
  SUCCESS_BATCH_JOB_DETAILS: "SUCCESS_BATCH_JOB_DETAILS",
  FAILURE_BATCH_JOB_DETAILS: "FAILURE_BATCH_JOB_DETAILS",
};

export const PLANNER_CONFIG = {
  CATEGORIES: {
    PLANNER_CONFIG_CATEGORIES_GET_REQUEST: "PLANNER_CONFIG_CATEGORIES_GET_REQUEST",
    PLANNER_CONFIG_CATEGORIES_GET_SUCCESS: "PLANNER_CONFIG_CATEGORIES_GET_SUCCESS",
    PLANNER_CONFIG_CATEGORIES_GET_FAILURE: "PLANNER_CONFIG_CATEGORIES_GET_FAILURE",

    PLANNER_CONFIG_CATEGORIES_CREATE_REQUEST: "PLANNER_CONFIG_CATEGORIES_CREATE_REQUEST",
    PLANNER_CONFIG_CATEGORIES_CREATE_SUCCESS: "PLANNER_CONFIG_CATEGORIES_CREATE_SUCCESS",
    PLANNER_CONFIG_CATEGORIES_CREATE_FAILURE: "PLANNER_CONFIG_CATEGORIES_CREATE_FAILURE",

    PLANNER_CONFIG_CATEGORIES_UPDATE_REQUEST: "PLANNER_CONFIG_CATEGORIES_UPDATE_REQUEST",
    PLANNER_CONFIG_CATEGORIES_UPDATE_SUCCESS: "PLANNER_CONFIG_CATEGORIES_UPDATE_SUCCESS",
    PLANNER_CONFIG_CATEGORIES_UPDATE_FAILURE: "PLANNER_CONFIG_CATEGORIES_UPDATE_FAILURE",
  },
};

export const RENDER_GET_DATA = "RENDER_GET_DATA";

export const INSIGHT_SERVICE_MANAGEMENT={
  REQUEST_FETCH_CONFIG_SETTINGS: "requestFetchConfigSettings",
  SUCCESS_FETCH_CONFIG_SETTINGS: "successFetchConfigSettings",
  FAILURE_FETCH_CONFIG_SETTINGS: "failureFetchConfigSettings",
}

export const renderGetData = (payload) => ({
  type: RENDER_GET_DATA,
  payload,
});
