// import { getCommandCategory } from "../services/jobs/JobsService";

const apiEndpoints = {
  auth: {
    // baseUrl: process.env.REACT_APP_AUTH_URL || "http://localhost:80",
    // baseUrl: process.env.REACT_APP_AUTH_URL || "https://localhost:5002",
    // baseUrl: process.env.REACT_APP_AUTH_URL || "https://predev.auth.rise.apps.jnj.com",
    baseUrl:
      process.env.REACT_APP_AUTH_URL || "https://dev.auth.rise.apps.jnj.com",
    post: {
      addGroup: "/v1/auth/groups/",
      addPermission: "/v1/auth/permissions/",
      addTask: "/v1/auth/tasks/",
      addApplication: "/v1/auth/rise-app/",
      authaction: "/auth/authaction",
    },
    get: {
      applicationList: "/v1/auth/rise-app/",
      taskList: "/v1/auth/tasks/",
      taskListByCategory: "/v1/auth/tasks/categories/",
      taskListBySubCategory: "/v1/auth/tasks/categories/subCategories",
      groupList: "/v1/auth/groups",
      permissionsByGroup: "/v1/auth/permissions/groups",
      users: "/v1/auth/users/",
      usersActivityLog: "/v1/auth/users/activity-log",
      groupExport: "/v1/auth/groups/export-csv",
      usersExport: "/v1/auth/users/export-csv",
      auditLog: "/v1/auth/audit",
      getSubCategory: "/v1/auth/subCategory",
      getAuditLogForCSV: "/v1/auth/audit/export",
      getParentGroups: "/v1/auth/groups/parent-groups",
      getAvailableParentGroups: "/v1/auth/groups/available-parents",
    },
    del: {
      deletePermission: "/v1/auth/permissions/",
      deleteGroup: "/v1/auth/groups/",
      deleteTask: "/v1/auth/tasks/",
      deleteApplication: "/v1/auth/rise-app/",
    },
    patch: {
      updateGroup: "/v1/auth/groups",
      updatePermission: "/v1/auth/permissions",
      updateTask: "/v1/auth/tasks",
      updateUser: "/v1/auth/users",
      refreshToken: "/v1/auth/refresh-token",
      logout: "/v1/auth/logout",
      updateApplication: "/v1/auth/rise-app/",
      blockApplication: "/v1/auth/rise-app/block",
      updateHelpContent: "/v1/auth/helpcontent",
    },
  },
  utilities: {
    baseUrl:
      process.env.REACT_APP_UTILITIES_URL ||
      "https://dev.utilities.rise.apps.jnj.com",
    get: {
      housekeepingList: "/v1/utilities/housekeeping/",
      changeNumberValidation: "/v1/utilities/cr/validate",
      batchSuggestionsList: "/v1/utilities/batch-operation/suggestions",
      getLogStatus: "v1/utilities/service-logs/check-logStatus",
      activityURL: "/v1/utilities/activity-log",
      auditLog: "/v1/utilities/audits",
      auditLogExport: "/v1/utilities/audits/export",
      helpContentList: "/v1/utilities/helpcontent/",
      helpContentListSubTitle: "/v1/utilities/helpcontent/subtitle",
      helpContentListSubTitlePublic: "/v1/utilities/helpcontentPublic/subtitle",
      searchContentList: "/v1/utilities/helpcontent",
      projectCategoryList: "/v1/utilities/helpcontent/project_category",
      projectCategoryListPublic:
        "/v1/utilities/helpcontentPublic/project_category",
      getMetricsData: "/v1/utilities/activity-log/access-metrics",
      getDownloadMetricsData: "/v1/utilities/activity-log/download-metrics",
      getSuggestionsActivityLog: "/v1/utilities/activity-log/suggestions",
      getUsersActivityLog: "/v1/utilities/activity-log/users",
      getVideosAWS: "/v1/utilities/helpcontent/videos",
      getVideoLink: "/v1/utilities/download/file-content",
      getHelpDocumentPublic: "/v1/utilities/helpcontentPublic/records",
      getAdvanceMetrics: "/v1/utilities/activity-log/detailed-metrics",
      getUTMCostSetting: "/v1/utilities/settings/config/",
    },
    post: {
      housekeeping: "/v1/utilities/housekeeping/",
      batchOperation: "/v1/utilities/batch-operation",
      createBlackoutId: "v1/utilities/ovo-blackout",
      changeLogStatus: "v1/utilities/service-logs/log-status",
      addHelpContent: "/v1/utilities/helpcontent/",
      projectCategoryList: "/v1/utilities/helpcontent/project_category",
      addVideosAWS: "/v1/utilities/upload",
      addUTMCostSetting: "/v1/utilities/settings/config",
    },
    del: {
      deleteHelpContent: "/v1/utilities/helpcontent",
      projectCategoryList: "/v1/utilities/helpcontent/project_category",
      deleteVideoAWS: "/v1/utilities/helpcontent/videos",
    },
    patch: {
      updateHelpContent: "/v1/utilities/helpcontent",
      projectCategoryList: "/v1/utilities/helpcontent/project_category",
      updateUTMCostSetting: "/v1/utilities/settings/config/",
    },
  },
  reports: {
    baseUrl: process.env.REACT_APP_BACKEND_URL || "http://localhost:3001",
    get: {
      getReports: "/reports/handleListReports",
    },
  },
  jobs: {
    baseUrl: process.env.REACT_APP_BACKEND_URL || "http://localhost:3001",
    post: {
      createJob: "/jobs/handleJob",
      createHost: "/jobs/handleHost",
      createCategory: "/jobs/handleCategory",
      createOpenSearchIndex: "/jobs/handleOpenSearchIndex",
      validateCronExpression: "/jobs/validateCronExpression",
      createCommandCategory: "/jobs/handleCommandCategory",
      publishReports: "/report/handlePublishReport",
      authaction: "/auth/authaction",
      internalJobs: "/app-config/add-internal-job",
      executeAdhocJob: "/jobs/executeAdhocJob",
      userConfiguration: "/jobs/handleUserConfiguration",
      bulkAgentAction: "/app-config/bulkAgentAction",
      // pauseResumeJobAction:"/jobs/pause-resume",
      handlejobRunning: "/schedule-status/pause-resume",
      publishAsSystemConfiguration: "/jobs/handlePublishAsSystemConfiguration",
      createCMDBSchedule: "/cmdb/createCMDBSchedule",
      cmdbConfiguration: "/jobs/handleCmdbConfiguration",
      handleExportSapFacts:"jobs/handleExportSapFacts"
    },
    put: {
      appConfig: "app-config/config",
      internalJobs: "app-config/update-internal-job",
      updateSapFactsColumns: "/jobs/updateSapFactsColumns",
    },
    get: {
      getJobs: "/jobs/getJobDetails",
      getJobFilterOptions: "/jobs/getJobFilterOptions",
      getScheduleDescriptions: "/jobs/getScheduleDescriptions",
      getHosts: "/jobs/getHosts",
      getSapFactHosts: "/jobs/getSapFactHosts",
      getCategories: "/jobs/getCategories",
      getCategoriesFilterOptions: "/jobs/getCategoriesFilterOptions",
      getTags: "/jobs/getTags",
      getTargets: "/jobs/getTargets",
      getHostDetail: "/jobs/getHostDetail",
      getHostFilterOptions: "/jobs/getSAPFactFilterOptions",
      getFrequencies: "/jobs/getFrequency",
      getHostById: "jobs/getHostById",
      getCategoryById: "jobs/getCategoryById",
      getOpenSearchIndexById: "jobs/getOpenSearchIndexById",
      getJobsByTags: "jobs/getJobsByTags",
      getSingleJob: "jobs/getJobDetailsById",
      getCommandCategory: "jobs/getCommandCategory",
      getCommandCategoryById: "jobs/getCommandCategoryById",
      getOpenSearchIndex: "jobs/getOpenSearchIndex",
      getServerTypes: "jobs/getServerTypes",
      getFilterValue: "jobs/getFilterValue",
      getLogFilters: "jobs/getLogFilters",
      getReportsDetails: "/report/getReportDetailsById",
      getDistinctOsTypes: "jobs/getServerOsTypes",
      appConfig: "app-config/config",
      internalJobs: "app-config/get-internal-jobs",
      getOpenSearchIndexByRunId: "jobs/getOpenSearchIndexByRunId",
      getUsersList: "/auth/getUserList",
      getUsernamesList: "/auth/getUsernamesList",
      getApprovalFlowConfigs: "/approval-flow/handleListApprovalFlowConfigs",
      getIAMGroups: "/auth/getIAMGroups",
      userConfiguration: "/jobs/getUserConfiguration",
      getCMDBSchedules: "/cmdb/getCMDBSchedules",
      triggerCMDBSchedule: "/cmdb/triggerCMDBSchedule",
      getScheduleOptions: "/jobs/system-publish-options",
      getCMDBSchedulesLogs: "/cmdb/getCMDBLogs",
      getCMDBSchedulesLogsFilter: "/cmdb/getCMDBLogsFilter",
      publishAsSystemConfiguration: "/jobs/getPublishAsSystemConfiguration",
      getAllWorkflows: "/api/workflow/app-workflow/workflow/all",
      syncSAPFactsCloumns: "/jobs/syncSAPFactsCloumns",
      getSapFactsColumns: "/jobs/getSapFactsColumns",
      cmdbConfiguration: "/jobs/getCmdbConfiguration",
      getCmdbConfigurationOptions: "/jobs/getCmdbConfigurationOptions",
    },
    del: {
      deleteJob: "/jobs/deleteJob",
      deleteAgentJob: "/app-config/job",
      deleteHost: "/jobs/deleteHost",
      deleteCategory: "/jobs/deleteCategory",
      deleteOpenSearchIndex: "/jobs/deleteOpenSearchIndex",
      deleteCommandCategory: "/jobs/deleteCommandCategory",
      deleteInternalJobs: "app-config/delete-internal-job",
      deleteUserConfiguration: "/jobs/deleteUserConfiguration",
      deletePublishAsSystem: "/jobs/deletePublishAsSystem",
      deleteCMDBConfiguration: "/jobs/deleteCmdbconf",
      deleteCmdbJob: "/cmdb/deleteCmdbJob",
    },
  },
  approvals: {
    baseUrl: process.env.REACT_APP_BACKEND_URL || "http://localhost:3001",
    post: {
      createUpdateApprovalFlowConfig: "/approval-flow/handleApprovalFlowConfig",
      approveRejectRequest: "/approval-flow/handleApproveRejectRequest",
      bulkApproveReject: "/approval-flow/handleBulkApproveReject",
    },
    del: {
      deleteApprovalConfig: "/approval-flow/handleDeleteApprovalFlowConfig",
    },
    get: {
      requestStatusList: "/approval-flow/handleListRequestStatus",
      approvalRequests: "/approval-flow/handleListApprovalRequests",
      listApprovalRequests: "/approval-flow/handleListApprovalRequests",
    },
  },
  others: {
    cmdb_instance: process.env.CMDB_INSTANCE || "",
  },
};

export default apiEndpoints;
